version: "3.7"
services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      # - 21027:21027/udp # Receive local discovery broadcasts
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/syncthing:/config
      - /mnt/syncthing/data:/data
  # 自建syncthing发现服务器
  syncthing-discovery:
    image: syncthing/discosrv:latest
    container_name: syncthing-discovery
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/syncthing-discovery:/config
    ports:
      - 8443:8443
  # 自建中继服务器
  syncthing-relay:
    image: syncthing/relaysrv:latest
    container_name: syncthing-relay
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - /mnt/syncthing/relay:/config
    ports:
      - 22067:22067