---
version: '3'
services:
  qbittorrent:
    image: dockerproxy.net/linuxserver/qbittorrent:4.5.5
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=16881
    volumes:
      - /share/CACHEDEV1_DATA/Container/qbittorrent/config:/config
      - /share/hliblack:/downloads
    ports:
      - 8080:8080
      - 16881:16881
      - 16881:16881/udp
    restart: unless-stopped