---
version: '3'
services:
  qbittorrent:
    image: dockerproxy.net/linuxserver/qbittorrent:4.5.5
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=26881
    volumes:
      - /share/CACHEDEV1_DATA/Container/qbittorrent/config:/config
      - /share/CACHEDEV2_DATA/hliblack:/download
    ports:
      - 8080:8080
      - 26881:26881
      - 26881:26881/udp
    restart: unless-stopped