kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-test
networking:
  ipFamily: ipv4
  apiServerAddress: 127.0.0.1
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  # the default CNI will not be installed
  disableDefaultCNI: true
  kubeProxyMode: "ipvs"
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 10080
    # optional: set the bind address on the host
    # 0.0.0.0 is the current default
    listenAddress: "0.0.0.0"
    # optional: set the protocol to one of TCP, UDP, SCTP.
    # TCP is the default
    protocol: TCP
  - containerPort: 443
    hostPort: 10443
    protocol: TCP
    listenAddress: "0.0.0.0"
  - containerPort: 10000
    hostPort: 10000
    protocol: TCP
    listenAddress: "0.0.0.0"
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 10080
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 443
    hostPort: 10443
    protocol: TCP
    listenAddress: "0.0.0.0"
  - containerPort: 10000
    hostPort: 10000
    protocol: TCP
    listenAddress: "0.0.0.0"
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 10080
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 443
    hostPort: 10443
    protocol: TCP
    listenAddress: "0.0.0.0"
  - containerPort: 10000
    hostPort: 10000
    protocol: TCP
    listenAddress: "0.0.0.0"
