# a cluster with 2 control-plane nodes and 3 workers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 180
    protocol: TCP
  - containerPort: 443
    hostPort: 1443
    protocol: TCP
  - containerPort: 30080
    hostPort: 10080
    protocol: TCP
  - containerPort: 30443
    hostPort: 10443
    protocol: TCP
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 280
    protocol: TCP
  - containerPort: 443
    hostPort: 2443
    protocol: TCP
  - containerPort: 30080
    hostPort: 20080
    protocol: TCP
  - containerPort: 30443
    hostPort: 20443
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 380
    protocol: TCP
  - containerPort: 443
    hostPort: 3443
    protocol: TCP
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  - containerPort: 30443
    hostPort: 30443
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 480
    protocol: TCP
  - containerPort: 443
    hostPort: 4443
    protocol: TCP
  - containerPort: 30080
    hostPort: 40080
    protocol: TCP
  - containerPort: 30443
    hostPort: 40443
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 580
    protocol: TCP
  - containerPort: 443
    hostPort: 5443
    protocol: TCP
  - containerPort: 30080
    hostPort: 55080
    protocol: TCP
  - containerPort: 30443
    hostPort: 55443
    protocol: TCP
