version: "3.7"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    user: "1000:100"
    restart: unless-stopped
    ports:
      - 7000:80
    environment:
      SIGNUPS_ALLOWED: "true"
      TZ: Asia/Shanghai
    volumes:
      - /share/CACHEDEV1_DATA/Container/vaultwarden:/data