version: v2
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /share/CACHEDEV1_DATA/Container/vaultwarden:/data
    ports:
      - 7000:80
    restart: unless-stopped
  