version: "3"
services:
  vaultwarden:
    image: docker.m.daocloud.io/vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /share/Container/vaultwarden:/data
    ports:
      - 7001:80
    restart: unless-stopped
  